# Generated by Django 2.1.7 on 2019-03-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messgae',
            new_name='message',
        ),
    ]
